export const heroTypes = ['common', 'rare', 'epic'];

const COMMON = heroTypes[0];
const RARE = heroTypes[1];
const EPIC = heroTypes[2];

export const heroes = [
  { name: 'Лучница', heroType: COMMON },
  { name: 'Кукловод', heroType: COMMON },
  { name: 'Варвар', heroType: COMMON },
  { name: 'Берсерк', heroType: COMMON },
  { name: 'Бомбометатель', heroType: COMMON },
  { name: 'Снежный лис', heroType: COMMON },
  { name: 'Гоблин', heroType: COMMON },
  { name: 'Голем', heroType: COMMON },
  { name: 'Рыцарь', heroType: COMMON },
  { name: 'Мыши-бандиты', heroType: COMMON },
  { name: 'Нага', heroType: COMMON },
  { name: 'Пират', heroType: COMMON },
  { name: 'Воин', heroType: COMMON },
  { name: 'Сатир', heroType: COMMON },
  { name: 'Скелет', heroType: COMMON },
  { name: 'Молотоборец', heroType: COMMON },
  { name: 'Энт', heroType: COMMON },
  { name: 'Броненосец', heroType: COMMON },
  { name: 'Йети', heroType: COMMON },
  { name: 'Убийца', heroType: RARE },
  { name: 'Банши', heroType: RARE },
  { name: 'Кузнец', heroType: RARE },
  { name: 'Сектант', heroType: RARE },
  { name: 'Пламя', heroType: RARE },
  { name: 'Гигант', heroType: RARE },
  { name: 'Ягуар', heroType: RARE },
  { name: 'Конг', heroType: RARE },
  { name: 'Орк', heroType: RARE },
  { name: 'Паладин', heroType: RARE },
  { name: 'Феникс', heroType: RARE },
  { name: 'Робот', heroType: RARE },
  { name: 'Снежная королева', heroType: RARE },
  { name: 'Волшебница', heroType: RARE },
  { name: 'Божество грома', heroType: RARE },
  { name: 'Волшебник', heroType: RARE },
  { name: 'Зомби', heroType: RARE },
  { name: 'Драконыш', heroType: EPIC },
  { name: 'Друид', heroType: EPIC },
  { name: 'Чародейка', heroType: EPIC },
  { name: 'Таинственная лягушка', heroType: EPIC },
  { name: 'Джин', heroType: EPIC },
  { name: 'Страж', heroType: EPIC },
  { name: 'Священник', heroType: EPIC },
  { name: 'Ракетчик', heroType: EPIC },
  { name: 'Шаман', heroType: EPIC },
  { name: 'Вампир', heroType: EPIC },
  { name: 'Призрак', heroType: EPIC },
];
